repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
        language: system
      # Run the formatter.
      - id: ruff-format
        language: system

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.20.0
      hooks:
      -   id: pyupgrade
          args: [--py311-plus]

  - repo: https://github.com/simone-viozzi/rusty-todo-md-pre-commit
    rev: v1.7.5
    hooks:
      - id: rusty-todo-md
